name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: snok/install-poetry@v1
        with:
          version: "2.3.4"

      - name: Install dependencies
        run: poetry install --only dev

      - name: Run Ruff lint
        run: poetry run ruff check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: snok/install-poetry@v1
        with:
          version: "2.3.4"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests
        run: poetry run pytest --cov=src
